// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../../../index.js";

export interface GroupsListResponse {
    tagGroups: IcePanel.TagGroup[];
}

export interface GroupsCreateResponse {
    tagGroup: IcePanel.TagGroup;
}

export interface GroupsGetResponse {
    tagGroup: IcePanel.TagGroup;
}

export interface GroupsUpsertResponse {
    tagGroup: IcePanel.TagGroup;
}

export interface GroupsDeleteResponse {
    commit: number;
}

export interface GroupsUpdateResponse {
    tagGroup: IcePanel.TagGroup;
}
