// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as IcePanel from "../../../index.js";
import { ContentClient } from "../resources/content/client/Client.js";
import { ExportClient } from "../resources/export/client/Client.js";
import { GroupsClient } from "../resources/groups/client/Client.js";

export declare namespace DiagramsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DiagramsClient {
    protected readonly _options: NormalizedClientOptions<DiagramsClient.Options>;
    protected _content: ContentClient | undefined;
    protected _groups: GroupsClient | undefined;
    protected _export: ExportClient | undefined;

    constructor(options: DiagramsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get content(): ContentClient {
        return (this._content ??= new ContentClient(this._options));
    }

    public get groups(): GroupsClient {
        return (this._groups ??= new GroupsClient(this._options));
    }

    public get export(): ExportClient {
        return (this._export ??= new ExportClient(this._options));
    }

    /**
     * @param {IcePanel.DiagramsListRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.list({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId"
     *     })
     */
    public list(
        request: IcePanel.DiagramsListRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DiagramsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: IcePanel.DiagramsListRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DiagramsListResponse>> {
        const { landscapeId, versionId, filter } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (filter != null) {
            _queryParams.filter = filter;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DiagramsListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams",
        );
    }

    /**
     * @param {IcePanel.DiagramCreateRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.create({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         index: 1.1,
     *         modelId: "modelId",
     *         name: "name",
     *         type: "app-diagram"
     *     })
     */
    public create(
        request: IcePanel.DiagramCreateRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DiagramsCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: IcePanel.DiagramCreateRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DiagramsCreateResponse>> {
        const { landscapeId, versionId, updateViewedAt, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (updateViewedAt != null) {
            _queryParams.updateViewedAt = updateViewedAt.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DiagramsCreateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams",
        );
    }

    /**
     * @param {IcePanel.DiagramFindRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.get({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         diagramId: "diagramId"
     *     })
     */
    public get(
        request: IcePanel.DiagramFindRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DiagramsGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: IcePanel.DiagramFindRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DiagramsGetResponse>> {
        const { landscapeId, versionId, diagramId, updateViewedAt } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (updateViewedAt != null) {
            _queryParams.updateViewedAt = updateViewedAt.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams/${core.url.encodePathParam(diagramId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DiagramsGetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams/{diagramId}",
        );
    }

    /**
     * @param {IcePanel.DiagramUpsertRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.ConflictError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.upsert({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         diagramId: "diagramId",
     *         index: 1.1,
     *         modelId: "modelId",
     *         name: "name",
     *         type: "app-diagram"
     *     })
     */
    public upsert(
        request: IcePanel.DiagramUpsertRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DiagramsUpsertResponse> {
        return core.HttpResponsePromise.fromPromise(this.__upsert(request, requestOptions));
    }

    private async __upsert(
        request: IcePanel.DiagramUpsertRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DiagramsUpsertResponse>> {
        const { landscapeId, versionId, diagramId, updateViewedAt, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (updateViewedAt != null) {
            _queryParams.updateViewedAt = updateViewedAt.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams/${core.url.encodePathParam(diagramId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DiagramsUpsertResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new IcePanel.ConflictError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams/{diagramId}",
        );
    }

    /**
     * @param {IcePanel.DiagramDeleteRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.delete({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         diagramId: "diagramId"
     *     })
     */
    public delete(
        request: IcePanel.DiagramDeleteRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DiagramsDeleteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: IcePanel.DiagramDeleteRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DiagramsDeleteResponse>> {
        const { landscapeId, versionId, diagramId, updateViewedAt } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (updateViewedAt != null) {
            _queryParams.updateViewedAt = updateViewedAt.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams/${core.url.encodePathParam(diagramId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DiagramsDeleteResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams/{diagramId}",
        );
    }

    /**
     * @param {IcePanel.DiagramUpdateRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.ConflictError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.update({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         diagramId: "diagramId"
     *     })
     */
    public update(
        request: IcePanel.DiagramUpdateRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DiagramsUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: IcePanel.DiagramUpdateRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DiagramsUpdateResponse>> {
        const { landscapeId, versionId, diagramId, updateViewedAt, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (updateViewedAt != null) {
            _queryParams.updateViewedAt = updateViewedAt.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams/${core.url.encodePathParam(diagramId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DiagramsUpdateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new IcePanel.ConflictError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams/{diagramId}",
        );
    }

    /**
     * @param {IcePanel.DiagramExistsRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.exists({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         diagramId: "diagramId"
     *     })
     */
    public exists(
        request: IcePanel.DiagramExistsRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<Headers> {
        return core.HttpResponsePromise.fromPromise(this.__exists(request, requestOptions));
    }

    private async __exists(
        request: IcePanel.DiagramExistsRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Headers>> {
        const { landscapeId, versionId, diagramId, updateViewedAt } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (updateViewedAt != null) {
            _queryParams.updateViewedAt = updateViewedAt.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams/${core.url.encodePathParam(diagramId)}`,
            ),
            method: "HEAD",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.rawResponse.headers, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "HEAD",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams/{diagramId}",
        );
    }

    /**
     * @param {IcePanel.DiagramThumbnailsListRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.listThumbnails({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId"
     *     })
     */
    public listThumbnails(
        request: IcePanel.DiagramThumbnailsListRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DiagramsListThumbnailsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listThumbnails(request, requestOptions));
    }

    private async __listThumbnails(
        request: IcePanel.DiagramThumbnailsListRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DiagramsListThumbnailsResponse>> {
        const { landscapeId, versionId, filter } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (filter != null) {
            _queryParams.filter = filter;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams/thumbnails`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as IcePanel.DiagramsListThumbnailsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams/thumbnails",
        );
    }

    /**
     * @param {IcePanel.DiagramThumbnailGetRequest} request
     * @param {DiagramsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.diagrams.getThumbnail({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         diagramId: "diagramId"
     *     })
     */
    public getThumbnail(
        request: IcePanel.DiagramThumbnailGetRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DiagramsGetThumbnailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getThumbnail(request, requestOptions));
    }

    private async __getThumbnail(
        request: IcePanel.DiagramThumbnailGetRequest,
        requestOptions?: DiagramsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DiagramsGetThumbnailResponse>> {
        const { landscapeId, versionId, diagramId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/diagrams/${core.url.encodePathParam(diagramId)}/thumbnail`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as IcePanel.DiagramsGetThumbnailResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/diagrams/{diagramId}/thumbnail",
        );
    }
}
