// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as IcePanel from "../../../index.js";

export declare namespace DomainsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DomainsClient {
    protected readonly _options: NormalizedClientOptions<DomainsClient.Options>;

    constructor(options: DomainsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {IcePanel.DomainsListRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.domains.list({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId"
     *     })
     */
    public list(
        request: IcePanel.DomainsListRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DomainsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: IcePanel.DomainsListRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DomainsListResponse>> {
        const { landscapeId, versionId, filter } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (filter != null) {
            _queryParams.filter = filter;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/domains`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DomainsListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/domains",
        );
    }

    /**
     * @param {IcePanel.DomainCreateRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.TooManyRequestsError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.domains.create({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         body: {
     *             name: "name"
     *         }
     *     })
     */
    public create(
        request: IcePanel.DomainCreateRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DomainsCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: IcePanel.DomainCreateRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DomainsCreateResponse>> {
        const { landscapeId, versionId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/domains`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DomainsCreateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new IcePanel.TooManyRequestsError(
                        _response.error.body as IcePanel.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/landscapes/{landscapeId}/versions/{versionId}/domains",
        );
    }

    /**
     * @param {IcePanel.DomainFindRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.domains.get({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         domainId: "domainId"
     *     })
     */
    public get(
        request: IcePanel.DomainFindRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DomainsGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: IcePanel.DomainFindRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DomainsGetResponse>> {
        const { landscapeId, versionId, domainId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/domains/${core.url.encodePathParam(domainId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DomainsGetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/domains/{domainId}",
        );
    }

    /**
     * @param {IcePanel.DomainUpsertRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.ConflictError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.TooManyRequestsError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.domains.upsert({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         domainId: "domainId",
     *         name: "name"
     *     })
     */
    public upsert(
        request: IcePanel.DomainUpsertRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DomainsUpsertResponse> {
        return core.HttpResponsePromise.fromPromise(this.__upsert(request, requestOptions));
    }

    private async __upsert(
        request: IcePanel.DomainUpsertRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DomainsUpsertResponse>> {
        const { landscapeId, versionId, domainId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/domains/${core.url.encodePathParam(domainId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DomainsUpsertResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new IcePanel.ConflictError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new IcePanel.TooManyRequestsError(
                        _response.error.body as IcePanel.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/landscapes/{landscapeId}/versions/{versionId}/domains/{domainId}",
        );
    }

    /**
     * @param {IcePanel.DomainDeleteRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.domains.delete({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         domainId: "domainId"
     *     })
     */
    public delete(
        request: IcePanel.DomainDeleteRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DomainsDeleteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: IcePanel.DomainDeleteRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DomainsDeleteResponse>> {
        const { landscapeId, versionId, domainId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/domains/${core.url.encodePathParam(domainId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DomainsDeleteResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/landscapes/{landscapeId}/versions/{versionId}/domains/{domainId}",
        );
    }

    /**
     * @param {IcePanel.DomainUpdateRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.ConflictError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.domains.update({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         domainId: "domainId",
     *         body: {}
     *     })
     */
    public update(
        request: IcePanel.DomainUpdateRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.DomainsUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: IcePanel.DomainUpdateRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.DomainsUpdateResponse>> {
        const { landscapeId, versionId, domainId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/domains/${core.url.encodePathParam(domainId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.DomainsUpdateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new IcePanel.ConflictError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/landscapes/{landscapeId}/versions/{versionId}/domains/{domainId}",
        );
    }

    /**
     * @param {IcePanel.DomainExistsRequest} request
     * @param {DomainsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.domains.exists({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         domainId: "domainId"
     *     })
     */
    public exists(
        request: IcePanel.DomainExistsRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): core.HttpResponsePromise<Headers> {
        return core.HttpResponsePromise.fromPromise(this.__exists(request, requestOptions));
    }

    private async __exists(
        request: IcePanel.DomainExistsRequest,
        requestOptions?: DomainsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Headers>> {
        const { landscapeId, versionId, domainId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.V1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/domains/${core.url.encodePathParam(domainId)}`,
            ),
            method: "HEAD",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.rawResponse.headers, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "HEAD",
            "/landscapes/{landscapeId}/versions/{versionId}/domains/{domainId}",
        );
    }
}
