// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../index.js";

export interface LandscapesGetResponse {
    landscape: IcePanel.Landscape;
}

export interface LandscapesUpdateResponse {
    landscape: IcePanel.Landscape;
}

export interface LandscapesDuplicateResponse {
    landscape: IcePanel.Landscape;
}

export interface LandscapesSearchResponse {
    results: IcePanel.SearchResult[];
}
