// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../../../index.js";

export interface ExportCreateResponse {
    landscapeExport: IcePanel.LandscapeExport;
}

export interface ExportGetResponse {
    landscapeExport: IcePanel.LandscapeExport;
}
