// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../index.js";

export interface FlowsListResponse {
    flows: IcePanel.Flow[];
}

export interface FlowsCreateResponse {
    flow: IcePanel.Flow;
}

export interface FlowsGetResponse {
    flow: IcePanel.Flow;
}

export interface FlowsUpsertResponse {
    flow: IcePanel.Flow;
}

export interface FlowsDeleteResponse {
    commit: number;
}

export interface FlowsUpdateResponse {
    flow: IcePanel.Flow;
}

export interface FlowsListThumbnailsResponse {
    thumbnails: Record<string, IcePanel.FlowThumbnail>;
}

export interface FlowsGetThumbnailResponse {
    thumbnail: IcePanel.FlowThumbnail;
}
