// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../../src/api/index";
import { IcePanelClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("GroupsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            diagramGroups: [
                {
                    commit: 1.1,
                    index: 1.1,
                    labels: { key: "value" },
                    modelId: "modelId",
                    name: "name",
                    handleId: "handleId",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    id: "id",
                    landscapeId: "landscapeId",
                    latestEntityId: "latestEntityId",
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    version: 1.1,
                    versionId: "versionId",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.diagrams.groups.list({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual({
            diagramGroups: [
                {
                    commit: 1.1,
                    index: 1.1,
                    labels: {
                        key: "value",
                    },
                    modelId: "modelId",
                    name: "name",
                    handleId: "handleId",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    id: "id",
                    landscapeId: "landscapeId",
                    latestEntityId: "latestEntityId",
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    version: 1.1,
                    versionId: "versionId",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = {
            diagramGroup: {
                commit: 1.1,
                index: 1.1,
                labels: { key: "value" },
                modelId: "modelId",
                name: "name",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.diagrams.groups.create({
            landscapeId: "landscapeId",
            versionId: "versionId",
            body: {
                modelId: "modelId",
                name: "name",
            },
        });
        expect(response).toEqual({
            diagramGroup: {
                commit: 1.1,
                index: 1.1,
                labels: {
                    key: "value",
                },
                modelId: "modelId",
                name: "name",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    modelId: "modelId",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    modelId: "modelId",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    modelId: "modelId",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    modelId: "modelId",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/diagram-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    modelId: "modelId",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            diagramGroup: {
                commit: 1.1,
                index: 1.1,
                labels: { key: "value" },
                modelId: "modelId",
                name: "name",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.diagrams.groups.get({
            landscapeId: "landscapeId",
            versionId: "versionId",
            diagramGroupId: "diagramGroupId",
        });
        expect(response).toEqual({
            diagramGroup: {
                commit: 1.1,
                index: 1.1,
                labels: {
                    key: "value",
                },
                modelId: "modelId",
                name: "name",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("upsert (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = {
            diagramGroup: {
                commit: 1.1,
                index: 1.1,
                labels: { key: "value" },
                modelId: "modelId",
                name: "name",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.diagrams.groups.upsert({
            landscapeId: "landscapeId",
            versionId: "versionId",
            diagramGroupId: "diagramGroupId",
            modelId: "modelId",
            name: "name",
        });
        expect(response).toEqual({
            diagramGroup: {
                commit: 1.1,
                index: 1.1,
                labels: {
                    key: "value",
                },
                modelId: "modelId",
                name: "name",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        });
    });

    test("upsert (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                modelId: "modelId",
                name: "name",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("upsert (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                modelId: "modelId",
                name: "name",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("upsert (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                modelId: "modelId",
                name: "name",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("upsert (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                modelId: "modelId",
                name: "name",
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("upsert (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                modelId: "modelId",
                name: "name",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("upsert (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                modelId: "modelId",
                name: "name",
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("upsert (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { modelId: "modelId", name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                modelId: "modelId",
                name: "name",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { commit: 1.1 };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.diagrams.groups.delete({
            landscapeId: "landscapeId",
            versionId: "versionId",
            diagramGroupId: "diagramGroupId",
        });
        expect(response).toEqual({
            commit: 1.1,
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            diagramGroup: {
                commit: 1.1,
                index: 1.1,
                labels: { key: "value" },
                modelId: "modelId",
                name: "name",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.diagrams.groups.update({
            landscapeId: "landscapeId",
            versionId: "versionId",
            diagramGroupId: "diagramGroupId",
            body: {},
        });
        expect(response).toEqual({
            diagramGroup: {
                commit: 1.1,
                index: 1.1,
                labels: {
                    key: "value",
                },
                modelId: "modelId",
                name: "name",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("exists (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(200)
            .build();

        const headers = await client.diagrams.groups.exists({
            landscapeId: "landscapeId",
            versionId: "versionId",
            diagramGroupId: "diagramGroupId",
        });
        expect(headers).toBeInstanceOf(Headers);
    });

    test("exists (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.exists({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("exists (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.exists({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("exists (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.exists({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("exists (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/diagram-groups/diagramGroupId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.diagrams.groups.exists({
                landscapeId: "landscapeId",
                versionId: "versionId",
                diagramGroupId: "diagramGroupId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });
});
