// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../index.js";

export interface DomainsListResponse {
    domains: IcePanel.Domain[];
}

export interface DomainsCreateResponse {
    domain: IcePanel.Domain;
}

export interface DomainsGetResponse {
    domain: IcePanel.Domain;
}

export interface DomainsUpsertResponse {
    domain: IcePanel.Domain;
}

export interface DomainsDeleteResponse {
    commit: number;
}

export interface DomainsUpdateResponse {
    domain: IcePanel.Domain;
}
