// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../../src/api/index";
import { IcePanelClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ConnectionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            modelConnections: [
                {
                    commit: 1.1,
                    description: "description",
                    direction: "outgoing",
                    labels: { key: "value" },
                    links: { key: { index: 1.1, id: "id" } },
                    name: "name",
                    originId: "originId",
                    status: "deprecated",
                    tagIds: ["tagIds"],
                    targetId: "targetId",
                    technologyIds: ["technologyIds"],
                    viaId: "viaId",
                    handleId: "handleId",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    diagrams: {
                        key: {
                            connectionId: "connectionId",
                            id: "id",
                            originModelId: "originModelId",
                            targetModelId: "targetModelId",
                        },
                    },
                    flows: { key: { id: "id", stepId: "stepId" } },
                    id: "id",
                    landscapeId: "landscapeId",
                    latestEntityId: "latestEntityId",
                    linked: true,
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    version: 1.1,
                    versionId: "versionId",
                    tags: { key: { color: "color", groupId: "groupId", id: "id", name: "name" } },
                    technologies: { key: { color: "blue", id: "id", name: "name" } },
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.model.connections.list({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual({
            modelConnections: [
                {
                    commit: 1.1,
                    description: "description",
                    direction: "outgoing",
                    labels: {
                        key: "value",
                    },
                    links: {
                        key: {
                            index: 1.1,
                            id: "id",
                        },
                    },
                    name: "name",
                    originId: "originId",
                    status: "deprecated",
                    tagIds: ["tagIds"],
                    targetId: "targetId",
                    technologyIds: ["technologyIds"],
                    viaId: "viaId",
                    handleId: "handleId",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    diagrams: {
                        key: {
                            connectionId: "connectionId",
                            id: "id",
                            originModelId: "originModelId",
                            targetModelId: "targetModelId",
                        },
                    },
                    flows: {
                        key: {
                            id: "id",
                            stepId: "stepId",
                        },
                    },
                    id: "id",
                    landscapeId: "landscapeId",
                    latestEntityId: "latestEntityId",
                    linked: true,
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    version: 1.1,
                    versionId: "versionId",
                    tags: {
                        key: {
                            color: "color",
                            groupId: "groupId",
                            id: "id",
                            name: "name",
                        },
                    },
                    technologies: {
                        key: {
                            color: "blue",
                            id: "id",
                            name: "name",
                        },
                    },
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", originId: "originId", targetId: "targetId" };
        const rawResponseBody = {
            modelConnection: {
                commit: 1.1,
                description: "description",
                direction: "outgoing",
                labels: { key: "value" },
                links: { key: { index: 1.1, id: "id" } },
                name: "name",
                originId: "originId",
                status: "deprecated",
                tagIds: ["tagIds"],
                targetId: "targetId",
                technologyIds: ["technologyIds"],
                viaId: "viaId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: {
                    key: {
                        connectionId: "connectionId",
                        id: "id",
                        originModelId: "originModelId",
                        targetModelId: "targetModelId",
                    },
                },
                flows: { key: { id: "id", stepId: "stepId" } },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                linked: true,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/model/connections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.model.connections.create({
            landscapeId: "landscapeId",
            versionId: "versionId",
            body: {
                name: "name",
                originId: "originId",
                targetId: "targetId",
            },
        });
        expect(response).toEqual({
            modelConnection: {
                commit: 1.1,
                description: "description",
                direction: "outgoing",
                labels: {
                    key: "value",
                },
                links: {
                    key: {
                        index: 1.1,
                        id: "id",
                    },
                },
                name: "name",
                originId: "originId",
                status: "deprecated",
                tagIds: ["tagIds"],
                targetId: "targetId",
                technologyIds: ["technologyIds"],
                viaId: "viaId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: {
                    key: {
                        connectionId: "connectionId",
                        id: "id",
                        originModelId: "originModelId",
                        targetModelId: "targetModelId",
                    },
                },
                flows: {
                    key: {
                        id: "id",
                        stepId: "stepId",
                    },
                },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                linked: true,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", originId: "originId", targetId: "targetId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/model/connections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    originId: "originId",
                    targetId: "targetId",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", originId: "originId", targetId: "targetId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/model/connections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    originId: "originId",
                    targetId: "targetId",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", originId: "originId", targetId: "targetId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/model/connections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    originId: "originId",
                    targetId: "targetId",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", originId: "originId", targetId: "targetId" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/model/connections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    originId: "originId",
                    targetId: "targetId",
                },
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", originId: "originId", targetId: "targetId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/model/connections")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    originId: "originId",
                    targetId: "targetId",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            modelConnection: {
                commit: 1.1,
                description: "description",
                direction: "outgoing",
                labels: { key: "value" },
                links: { key: { index: 1.1, id: "id" } },
                name: "name",
                originId: "originId",
                status: "deprecated",
                tagIds: ["tagIds"],
                targetId: "targetId",
                technologyIds: ["technologyIds"],
                viaId: "viaId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: {
                    key: {
                        connectionId: "connectionId",
                        id: "id",
                        originModelId: "originModelId",
                        targetModelId: "targetModelId",
                    },
                },
                flows: { key: { id: "id", stepId: "stepId" } },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                linked: true,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                tags: { key: { color: "color", groupId: "groupId", id: "id", name: "name" } },
                technologies: { key: { color: "blue", id: "id", name: "name" } },
            },
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.model.connections.get({
            landscapeId: "landscapeId",
            versionId: "versionId",
            modelConnectionId: "modelConnectionId",
        });
        expect(response).toEqual({
            modelConnection: {
                commit: 1.1,
                description: "description",
                direction: "outgoing",
                labels: {
                    key: "value",
                },
                links: {
                    key: {
                        index: 1.1,
                        id: "id",
                    },
                },
                name: "name",
                originId: "originId",
                status: "deprecated",
                tagIds: ["tagIds"],
                targetId: "targetId",
                technologyIds: ["technologyIds"],
                viaId: "viaId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: {
                    key: {
                        connectionId: "connectionId",
                        id: "id",
                        originModelId: "originModelId",
                        targetModelId: "targetModelId",
                    },
                },
                flows: {
                    key: {
                        id: "id",
                        stepId: "stepId",
                    },
                },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                linked: true,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                tags: {
                    key: {
                        color: "color",
                        groupId: "groupId",
                        id: "id",
                        name: "name",
                    },
                },
                technologies: {
                    key: {
                        color: "blue",
                        id: "id",
                        name: "name",
                    },
                },
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("upsert (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", originId: "originId", targetId: "targetId" };
        const rawResponseBody = {
            modelConnection: {
                commit: 1.1,
                description: "description",
                direction: "outgoing",
                labels: { key: "value" },
                links: { key: { index: 1.1, id: "id" } },
                name: "name",
                originId: "originId",
                status: "deprecated",
                tagIds: ["tagIds"],
                targetId: "targetId",
                technologyIds: ["technologyIds"],
                viaId: "viaId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: {
                    key: {
                        connectionId: "connectionId",
                        id: "id",
                        originModelId: "originModelId",
                        targetModelId: "targetModelId",
                    },
                },
                flows: { key: { id: "id", stepId: "stepId" } },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                linked: true,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.model.connections.upsert({
            landscapeId: "landscapeId",
            versionId: "versionId",
            modelConnectionId: "modelConnectionId",
            name: "name",
            originId: "originId",
            targetId: "targetId",
        });
        expect(response).toEqual({
            modelConnection: {
                commit: 1.1,
                description: "description",
                direction: "outgoing",
                labels: {
                    key: "value",
                },
                links: {
                    key: {
                        index: 1.1,
                        id: "id",
                    },
                },
                name: "name",
                originId: "originId",
                status: "deprecated",
                tagIds: ["tagIds"],
                targetId: "targetId",
                technologyIds: ["technologyIds"],
                viaId: "viaId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: {
                    key: {
                        connectionId: "connectionId",
                        id: "id",
                        originModelId: "originModelId",
                        targetModelId: "targetModelId",
                    },
                },
                flows: {
                    key: {
                        id: "id",
                        stepId: "stepId",
                    },
                },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                linked: true,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        });
    });

    test("upsert (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            direction: { key: "value" },
            links: { key: "value" },
            name: "name",
            originId: "originId",
            tagIds: { key: "value" },
            targetId: "targetId",
            technologyIds: { key: "value" },
            viaId: { key: "value" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                direction: {
                    key: "value",
                },
                links: {
                    key: "value",
                },
                name: "name",
                originId: "originId",
                tagIds: {
                    key: "value",
                },
                targetId: "targetId",
                technologyIds: {
                    key: "value",
                },
                viaId: {
                    key: "value",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("upsert (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            direction: { key: "value" },
            links: { key: "value" },
            name: "name",
            originId: "originId",
            tagIds: { key: "value" },
            targetId: "targetId",
            technologyIds: { key: "value" },
            viaId: { key: "value" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                direction: {
                    key: "value",
                },
                links: {
                    key: "value",
                },
                name: "name",
                originId: "originId",
                tagIds: {
                    key: "value",
                },
                targetId: "targetId",
                technologyIds: {
                    key: "value",
                },
                viaId: {
                    key: "value",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("upsert (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            direction: { key: "value" },
            links: { key: "value" },
            name: "name",
            originId: "originId",
            tagIds: { key: "value" },
            targetId: "targetId",
            technologyIds: { key: "value" },
            viaId: { key: "value" },
        };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                direction: {
                    key: "value",
                },
                links: {
                    key: "value",
                },
                name: "name",
                originId: "originId",
                tagIds: {
                    key: "value",
                },
                targetId: "targetId",
                technologyIds: {
                    key: "value",
                },
                viaId: {
                    key: "value",
                },
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("upsert (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            direction: { key: "value" },
            links: { key: "value" },
            name: "name",
            originId: "originId",
            tagIds: { key: "value" },
            targetId: "targetId",
            technologyIds: { key: "value" },
            viaId: { key: "value" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                direction: {
                    key: "value",
                },
                links: {
                    key: "value",
                },
                name: "name",
                originId: "originId",
                tagIds: {
                    key: "value",
                },
                targetId: "targetId",
                technologyIds: {
                    key: "value",
                },
                viaId: {
                    key: "value",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("upsert (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            direction: { key: "value" },
            links: { key: "value" },
            name: "name",
            originId: "originId",
            tagIds: { key: "value" },
            targetId: "targetId",
            technologyIds: { key: "value" },
            viaId: { key: "value" },
        };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                direction: {
                    key: "value",
                },
                links: {
                    key: "value",
                },
                name: "name",
                originId: "originId",
                tagIds: {
                    key: "value",
                },
                targetId: "targetId",
                technologyIds: {
                    key: "value",
                },
                viaId: {
                    key: "value",
                },
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("upsert (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            direction: { key: "value" },
            links: { key: "value" },
            name: "name",
            originId: "originId",
            tagIds: { key: "value" },
            targetId: "targetId",
            technologyIds: { key: "value" },
            viaId: { key: "value" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                direction: {
                    key: "value",
                },
                links: {
                    key: "value",
                },
                name: "name",
                originId: "originId",
                tagIds: {
                    key: "value",
                },
                targetId: "targetId",
                technologyIds: {
                    key: "value",
                },
                viaId: {
                    key: "value",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { commit: 1.1 };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.model.connections.delete({
            landscapeId: "landscapeId",
            versionId: "versionId",
            modelConnectionId: "modelConnectionId",
        });
        expect(response).toEqual({
            commit: 1.1,
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            modelConnection: {
                commit: 1.1,
                description: "description",
                direction: "outgoing",
                labels: { key: "value" },
                links: { key: { index: 1.1, id: "id" } },
                name: "name",
                originId: "originId",
                status: "deprecated",
                tagIds: ["tagIds"],
                targetId: "targetId",
                technologyIds: ["technologyIds"],
                viaId: "viaId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: {
                    key: {
                        connectionId: "connectionId",
                        id: "id",
                        originModelId: "originModelId",
                        targetModelId: "targetModelId",
                    },
                },
                flows: { key: { id: "id", stepId: "stepId" } },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                linked: true,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.model.connections.update({
            landscapeId: "landscapeId",
            versionId: "versionId",
            modelConnectionId: "modelConnectionId",
            body: {},
        });
        expect(response).toEqual({
            modelConnection: {
                commit: 1.1,
                description: "description",
                direction: "outgoing",
                labels: {
                    key: "value",
                },
                links: {
                    key: {
                        index: 1.1,
                        id: "id",
                    },
                },
                name: "name",
                originId: "originId",
                status: "deprecated",
                tagIds: ["tagIds"],
                targetId: "targetId",
                technologyIds: ["technologyIds"],
                viaId: "viaId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: {
                    key: {
                        connectionId: "connectionId",
                        id: "id",
                        originModelId: "originModelId",
                        targetModelId: "targetModelId",
                    },
                },
                flows: {
                    key: {
                        id: "id",
                        stepId: "stepId",
                    },
                },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                linked: true,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/model/connections/modelConnectionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.model.connections.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                modelConnectionId: "modelConnectionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });
});
