// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../../src/api/index";
import { IcePanelClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("LogsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            actionLogs: [
                {
                    action: { id: "id", props: { name: "name", permission: "billing" }, type: "api-key-create" },
                    actionIds: ["actionIds"],
                    id: "id",
                    importance: "low",
                    landscapeId: "landscapeId",
                    parentId: "parentId",
                    performedAt: "2024-01-15T09:30:00Z",
                    performedBy: "user",
                    performedById: "performedById",
                    performedByName: "performedByName",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.landscapes.logs.list({
            landscapeId: "landscapeId",
        });
        expect(response).toEqual({
            actionLogs: [
                {
                    action: {
                        id: "id",
                        props: {
                            name: "name",
                            permission: "billing",
                        },
                        type: "api-key-create",
                    },
                    actionIds: ["actionIds"],
                    id: "id",
                    importance: "low",
                    landscapeId: "landscapeId",
                    parentId: "parentId",
                    performedAt: "2024-01-15T09:30:00Z",
                    performedBy: "user",
                    performedById: "performedById",
                    performedByName: "performedByName",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            actionLog: {
                action: { id: "id", props: { name: "name", permission: "billing" }, type: "api-key-create" },
                actionIds: ["actionIds"],
                id: "id",
                importance: "low",
                landscapeId: "landscapeId",
                parentId: "parentId",
                performedAt: "2024-01-15T09:30:00Z",
                performedBy: "user",
                performedById: "performedById",
                performedByName: "performedByName",
            },
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.landscapes.logs.get({
            landscapeId: "landscapeId",
            actionLogId: "actionLogId",
        });
        expect(response).toEqual({
            actionLog: {
                action: {
                    id: "id",
                    props: {
                        name: "name",
                        permission: "billing",
                    },
                    type: "api-key-create",
                },
                actionIds: ["actionIds"],
                id: "id",
                importance: "low",
                landscapeId: "landscapeId",
                parentId: "parentId",
                performedAt: "2024-01-15T09:30:00Z",
                performedBy: "user",
                performedById: "performedById",
                performedByName: "performedByName",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.get({
                landscapeId: "landscapeId",
                actionLogId: "actionLogId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.get({
                landscapeId: "landscapeId",
                actionLogId: "actionLogId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.get({
                landscapeId: "landscapeId",
                actionLogId: "actionLogId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.get({
                landscapeId: "landscapeId",
                actionLogId: "actionLogId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("listChildren (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            actionLogs: [
                {
                    action: { id: "id", props: { name: "name", permission: "billing" }, type: "api-key-create" },
                    actionIds: ["actionIds"],
                    id: "id",
                    importance: "low",
                    landscapeId: "landscapeId",
                    parentId: "parentId",
                    performedAt: "2024-01-15T09:30:00Z",
                    performedBy: "user",
                    performedById: "performedById",
                    performedByName: "performedByName",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId/children")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.landscapes.logs.listChildren({
            landscapeId: "landscapeId",
            actionLogId: "actionLogId",
        });
        expect(response).toEqual({
            actionLogs: [
                {
                    action: {
                        id: "id",
                        props: {
                            name: "name",
                            permission: "billing",
                        },
                        type: "api-key-create",
                    },
                    actionIds: ["actionIds"],
                    id: "id",
                    importance: "low",
                    landscapeId: "landscapeId",
                    parentId: "parentId",
                    performedAt: "2024-01-15T09:30:00Z",
                    performedBy: "user",
                    performedById: "performedById",
                    performedByName: "performedByName",
                },
            ],
        });
    });

    test("listChildren (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId/children")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.listChildren({
                landscapeId: "landscapeId",
                actionLogId: "actionLogId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("listChildren (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId/children")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.listChildren({
                landscapeId: "landscapeId",
                actionLogId: "actionLogId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("listChildren (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId/children")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.listChildren({
                landscapeId: "landscapeId",
                actionLogId: "actionLogId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("listChildren (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/action-logs/actionLogId/children")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.landscapes.logs.listChildren({
                landscapeId: "landscapeId",
                actionLogId: "actionLogId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });
});
