// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../../../index.js";

export interface LogsListResponse {
    organizationLogs: IcePanel.OrganizationLog[];
}

export interface LogsGetResponse {
    organizationLog: IcePanel.OrganizationLog;
}
