// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../../../index.js";

export interface ConnectionsListResponse {
    modelConnections: IcePanel.ModelConnectionExpanded[];
}

export interface ConnectionsCreateResponse {
    modelConnection: IcePanel.ModelConnection;
}

export interface ConnectionsGetResponse {
    modelConnection: IcePanel.ModelConnectionExpanded;
}

export const ConnectionsUpsertRequestOriginConnector = {
    TopLeft: "top-left",
    TopCenter: "top-center",
    TopRight: "top-right",
    RightTop: "right-top",
    RightMiddle: "right-middle",
    RightBottom: "right-bottom",
    BottomRight: "bottom-right",
    BottomCenter: "bottom-center",
    BottomLeft: "bottom-left",
    LeftBottom: "left-bottom",
    LeftMiddle: "left-middle",
    LeftTop: "left-top",
} as const;
export type ConnectionsUpsertRequestOriginConnector =
    (typeof ConnectionsUpsertRequestOriginConnector)[keyof typeof ConnectionsUpsertRequestOriginConnector];

export const ConnectionsUpsertRequestTargetConnector = {
    TopLeft: "top-left",
    TopCenter: "top-center",
    TopRight: "top-right",
    RightTop: "right-top",
    RightMiddle: "right-middle",
    RightBottom: "right-bottom",
    BottomRight: "bottom-right",
    BottomCenter: "bottom-center",
    BottomLeft: "bottom-left",
    LeftBottom: "left-bottom",
    LeftMiddle: "left-middle",
    LeftTop: "left-top",
} as const;
export type ConnectionsUpsertRequestTargetConnector =
    (typeof ConnectionsUpsertRequestTargetConnector)[keyof typeof ConnectionsUpsertRequestTargetConnector];

export interface ConnectionsUpsertResponse {
    modelConnection: IcePanel.ModelConnection;
}

export interface ConnectionsDeleteResponse {
    commit: number;
}

export interface ConnectionsUpdateResponse {
    modelConnection: IcePanel.ModelConnection;
}
