// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../index.js";

export interface VersionsListResponse {
    versions: IcePanel.Version[];
}

export interface VersionsCreateResponse {
    version: IcePanel.Version;
}

export interface VersionsGetResponse {
    version: IcePanel.Version;
}

export interface VersionsUpdateResponse {
    version: IcePanel.Version;
}
