// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../src/api/index";
import { IcePanelClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("FlowsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            flows: [
                {
                    commit: 1.1,
                    index: 1.1,
                    labels: { key: "value" },
                    name: "name",
                    pinned: true,
                    pinnedAt: "2024-01-15T09:30:00Z",
                    pinnedIndex: 1.1,
                    showAllSteps: true,
                    showConnectionNames: true,
                    steps: { key: { description: "description", id: "id", index: 1.1 } },
                    diagramId: "diagramId",
                    handleId: "handleId",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    id: "id",
                    landscapeId: "landscapeId",
                    latestEntityId: "latestEntityId",
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    version: 1.1,
                    versionId: "versionId",
                    viewedAt: "2024-01-15T09:30:00Z",
                    viewedBy: "user",
                    viewedById: "viewedById",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.list({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual({
            flows: [
                {
                    commit: 1.1,
                    index: 1.1,
                    labels: {
                        key: "value",
                    },
                    name: "name",
                    pinned: true,
                    pinnedAt: "2024-01-15T09:30:00Z",
                    pinnedIndex: 1.1,
                    showAllSteps: true,
                    showConnectionNames: true,
                    steps: {
                        key: {
                            description: "description",
                            id: "id",
                            index: 1.1,
                        },
                    },
                    diagramId: "diagramId",
                    handleId: "handleId",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    id: "id",
                    landscapeId: "landscapeId",
                    latestEntityId: "latestEntityId",
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    version: 1.1,
                    versionId: "versionId",
                    viewedAt: "2024-01-15T09:30:00Z",
                    viewedBy: "user",
                    viewedById: "viewedById",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = {
            flow: {
                commit: 1.1,
                index: 1.1,
                labels: { key: "value" },
                name: "name",
                pinned: true,
                pinnedAt: "2024-01-15T09:30:00Z",
                pinnedIndex: 1.1,
                showAllSteps: true,
                showConnectionNames: true,
                steps: { key: { description: "description", id: "id", index: 1.1 } },
                diagramId: "diagramId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/flows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.create({
            landscapeId: "landscapeId",
            versionId: "versionId",
            body: {
                name: "name",
                diagramId: "diagramId",
            },
        });
        expect(response).toEqual({
            flow: {
                commit: 1.1,
                index: 1.1,
                labels: {
                    key: "value",
                },
                name: "name",
                pinned: true,
                pinnedAt: "2024-01-15T09:30:00Z",
                pinnedIndex: 1.1,
                showAllSteps: true,
                showConnectionNames: true,
                steps: {
                    key: {
                        description: "description",
                        id: "id",
                        index: 1.1,
                    },
                },
                diagramId: "diagramId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/flows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/flows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/flows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/flows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/flows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/flows")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            flow: {
                commit: 1.1,
                index: 1.1,
                labels: { key: "value" },
                name: "name",
                pinned: true,
                pinnedAt: "2024-01-15T09:30:00Z",
                pinnedIndex: 1.1,
                showAllSteps: true,
                showConnectionNames: true,
                steps: { key: { description: "description", id: "id", index: 1.1 } },
                diagramId: "diagramId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.get({
            landscapeId: "landscapeId",
            versionId: "versionId",
            flowId: "flowId",
        });
        expect(response).toEqual({
            flow: {
                commit: 1.1,
                index: 1.1,
                labels: {
                    key: "value",
                },
                name: "name",
                pinned: true,
                pinnedAt: "2024-01-15T09:30:00Z",
                pinnedIndex: 1.1,
                showAllSteps: true,
                showConnectionNames: true,
                steps: {
                    key: {
                        description: "description",
                        id: "id",
                        index: 1.1,
                    },
                },
                diagramId: "diagramId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("upsert (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = {
            flow: {
                commit: 1.1,
                index: 1.1,
                labels: { key: "value" },
                name: "name",
                pinned: true,
                pinnedAt: "2024-01-15T09:30:00Z",
                pinnedIndex: 1.1,
                showAllSteps: true,
                showConnectionNames: true,
                steps: { key: { description: "description", id: "id", index: 1.1 } },
                diagramId: "diagramId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.upsert({
            landscapeId: "landscapeId",
            versionId: "versionId",
            flowId: "flowId",
            body: {
                name: "name",
                diagramId: "diagramId",
            },
        });
        expect(response).toEqual({
            flow: {
                commit: 1.1,
                index: 1.1,
                labels: {
                    key: "value",
                },
                name: "name",
                pinned: true,
                pinnedAt: "2024-01-15T09:30:00Z",
                pinnedIndex: 1.1,
                showAllSteps: true,
                showConnectionNames: true,
                steps: {
                    key: {
                        description: "description",
                        id: "id",
                        index: 1.1,
                    },
                },
                diagramId: "diagramId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        });
    });

    test("upsert (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("upsert (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("upsert (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("upsert (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("upsert (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("upsert (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("upsert (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("upsert (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", diagramId: "diagramId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {
                    name: "name",
                    diagramId: "diagramId",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { commit: 1.1 };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.delete({
            landscapeId: "landscapeId",
            versionId: "versionId",
            flowId: "flowId",
        });
        expect(response).toEqual({
            commit: 1.1,
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            flow: {
                commit: 1.1,
                index: 1.1,
                labels: { key: "value" },
                name: "name",
                pinned: true,
                pinnedAt: "2024-01-15T09:30:00Z",
                pinnedIndex: 1.1,
                showAllSteps: true,
                showConnectionNames: true,
                steps: { key: { description: "description", id: "id", index: 1.1 } },
                diagramId: "diagramId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.update({
            landscapeId: "landscapeId",
            versionId: "versionId",
            flowId: "flowId",
            body: {},
        });
        expect(response).toEqual({
            flow: {
                commit: 1.1,
                index: 1.1,
                labels: {
                    key: "value",
                },
                name: "name",
                pinned: true,
                pinnedAt: "2024-01-15T09:30:00Z",
                pinnedIndex: 1.1,
                showAllSteps: true,
                showConnectionNames: true,
                steps: {
                    key: {
                        description: "description",
                        id: "id",
                        index: 1.1,
                    },
                },
                diagramId: "diagramId",
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("exists (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(200)
            .build();

        const headers = await client.flows.exists({
            landscapeId: "landscapeId",
            versionId: "versionId",
            flowId: "flowId",
        });
        expect(headers).toBeInstanceOf(Headers);
    });

    test("exists (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.exists({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("exists (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.exists({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("exists (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.exists({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("exists (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .head("/landscapes/landscapeId/versions/versionId/flows/flowId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.exists({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("listThumbnails (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            thumbnails: {
                key: {
                    createdAt: "2024-01-15T09:30:00Z",
                    diagramId: "diagramId",
                    expires: "2024-01-15T09:30:00Z",
                    handleId: "handleId",
                    id: "id",
                    name: "name",
                    updatedAt: "2024-01-15T09:30:00Z",
                    url: "url",
                },
            },
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/thumbnails")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.listThumbnails({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual({
            thumbnails: {
                key: {
                    createdAt: "2024-01-15T09:30:00Z",
                    diagramId: "diagramId",
                    expires: "2024-01-15T09:30:00Z",
                    handleId: "handleId",
                    id: "id",
                    name: "name",
                    updatedAt: "2024-01-15T09:30:00Z",
                    url: "url",
                },
            },
        });
    });

    test("listThumbnails (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/thumbnails")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.listThumbnails({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("listThumbnails (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/thumbnails")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.listThumbnails({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("listThumbnails (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/thumbnails")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.listThumbnails({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("listThumbnails (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/thumbnails")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.listThumbnails({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("getThumbnail (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            thumbnail: {
                createdAt: "2024-01-15T09:30:00Z",
                diagramId: "diagramId",
                expires: "2024-01-15T09:30:00Z",
                handleId: "handleId",
                id: "id",
                name: "name",
                updatedAt: "2024-01-15T09:30:00Z",
                url: "url",
            },
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId/thumbnail")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.flows.getThumbnail({
            landscapeId: "landscapeId",
            versionId: "versionId",
            flowId: "flowId",
        });
        expect(response).toEqual({
            thumbnail: {
                createdAt: "2024-01-15T09:30:00Z",
                diagramId: "diagramId",
                expires: "2024-01-15T09:30:00Z",
                handleId: "handleId",
                id: "id",
                name: "name",
                updatedAt: "2024-01-15T09:30:00Z",
                url: "url",
            },
        });
    });

    test("getThumbnail (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId/thumbnail")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.getThumbnail({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("getThumbnail (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId/thumbnail")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.getThumbnail({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("getThumbnail (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId/thumbnail")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.getThumbnail({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("getThumbnail (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/flows/flowId/thumbnail")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.flows.getThumbnail({
                landscapeId: "landscapeId",
                versionId: "versionId",
                flowId: "flowId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });
});
