// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../src/api/index";
import { IcePanelClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ShareLinkClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            shareLink: {
                password: "password",
                protected: true,
                draftId: "draftId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                shortId: "shortId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                versionId: "versionId",
            },
            stats: { totalVisitorCount: 1.1, viewedAt: "2024-01-15T09:30:00Z" },
            url: "url",
        };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shareLink.get({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual({
            shareLink: {
                password: "password",
                protected: true,
                draftId: "draftId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                shortId: "shortId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                versionId: "versionId",
            },
            stats: {
                totalVisitorCount: 1.1,
                viewedAt: "2024-01-15T09:30:00Z",
            },
            url: "url",
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { protected: true };
        const rawResponseBody = {
            shareLink: {
                password: "password",
                protected: true,
                draftId: "draftId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                shortId: "shortId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                versionId: "versionId",
            },
            url: "url",
        };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shareLink.create({
            landscapeId: "landscapeId",
            versionId: "versionId",
            body: {
                protected: true,
            },
        });
        expect(response).toEqual({
            shareLink: {
                password: "password",
                protected: true,
                draftId: "draftId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                shortId: "shortId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                versionId: "versionId",
            },
            url: "url",
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { protected: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    protected: true,
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { protected: true };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    protected: true,
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { protected: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    protected: true,
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { protected: true };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    protected: true,
                },
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { protected: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    protected: true,
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { protected: true };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    protected: true,
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shareLink.delete({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual({
            key: "value",
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/share-link")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            shareLink: {
                password: "password",
                protected: true,
                draftId: "draftId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                shortId: "shortId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                versionId: "versionId",
            },
        };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.shareLink.update({
            landscapeId: "landscapeId",
            versionId: "versionId",
            body: {},
        });
        expect(response).toEqual({
            shareLink: {
                password: "password",
                protected: true,
                draftId: "draftId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                shortId: "shortId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                versionId: "versionId",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKey: "test",
            authorization: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/share-link")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.shareLink.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });
});
