// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../index.js";

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface CommentsListRequest {
    landscapeId: string;
    versionId: string;
    status?: string | string[];
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             body: {
 *                 content: "content",
 *                 status: "open",
 *                 type: "question"
 *             }
 *         }
 *     }
 */
export interface CommentCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.CommentRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId"
 *     }
 */
export interface CommentFindRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId",
 *         body: {
 *             content: "content",
 *             status: "open",
 *             type: "question"
 *         }
 *     }
 */
export interface CommentUpsertRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
    body: IcePanel.CommentBody;
    commit?: number;
    mentionedUserIds?: string[];
    handleId?: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId"
 *     }
 */
export interface CommentDeleteRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId",
 *         body: {}
 *     }
 */
export interface CommentUpdateRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
    body: IcePanel.CommentPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface DiagramsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.DiagramFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         index: 1.1,
 *         modelId: "modelId",
 *         name: "name",
 *         type: "app-diagram"
 *     }
 */
export interface DiagramCreateRequest {
    landscapeId: string;
    versionId: string;
    updateViewedAt?: boolean;
    commit?: number;
    description?: string;
    groupId?: string | null;
    index: number;
    labels?: Record<string, string>;
    /** model object id this object belongs to */
    modelId: string;
    name: string;
    parentId?: string | null;
    pinned?: boolean;
    pinnedAt?: string;
    pinnedIndex?: number;
    status?: IcePanel.DiagramStatus;
    /** Custom zoom levels for specific model objects within the diagram. The key is the modelObjectId and the value is the diagram id. */
    zoomOverrides?: Record<string, string | null> | null;
    handleId?: string;
    type: IcePanel.DiagramType;
    comments?: Record<string, IcePanel.DiagramComment>;
    connections?: Record<string, IcePanel.DiagramConnection>;
    objects?: Record<string, IcePanel.DiagramObject>;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId"
 *     }
 */
export interface DiagramFindRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    updateViewedAt?: boolean;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId",
 *         index: 1.1,
 *         modelId: "modelId",
 *         name: "name",
 *         type: "app-diagram"
 *     }
 */
export interface DiagramUpsertRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    updateViewedAt?: boolean;
    commit?: number;
    description?: string;
    groupId?: string | null;
    index: number;
    labels?: Record<string, string>;
    /** model object id this object belongs to */
    modelId: string;
    name: string;
    parentId?: string | null;
    pinned?: boolean;
    pinnedAt?: string;
    pinnedIndex?: number;
    status?: IcePanel.DiagramStatus;
    /** Custom zoom levels for specific model objects within the diagram. The key is the modelObjectId and the value is the diagram id. */
    zoomOverrides?: Record<string, string | null> | null;
    handleId?: string;
    type: IcePanel.DiagramType;
    comments?: Record<string, IcePanel.DiagramComment>;
    connections?: Record<string, IcePanel.DiagramConnection>;
    objects?: Record<string, IcePanel.DiagramObject>;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId"
 *     }
 */
export interface DiagramDeleteRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    updateViewedAt?: boolean;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId"
 *     }
 */
export interface DiagramUpdateRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    updateViewedAt?: boolean;
    commit?: number;
    description?: string;
    groupId?: string | null;
    index?: number;
    labels?: Record<string, string>;
    /** model object id this object belongs to */
    modelId?: string;
    name?: string;
    parentId?: string | null;
    pinned?: boolean;
    pinnedAt?: string;
    pinnedIndex?: number;
    status?: IcePanel.DiagramStatus;
    /** Custom zoom levels for specific model objects within the diagram. The key is the modelObjectId and the value is the diagram id. */
    zoomOverrides?: Record<string, string | null> | null;
    comments?: IcePanel.DiagramContentPartialComments;
    connections?: IcePanel.DiagramContentPartialConnections;
    objects?: IcePanel.DiagramContentPartialObjects;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId"
 *     }
 */
export interface DiagramExistsRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    updateViewedAt?: boolean;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface DiagramThumbnailsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.DiagramFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId"
 *     }
 */
export interface DiagramThumbnailGetRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface DomainsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.DomainFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             name: "name"
 *         }
 *     }
 */
export interface DomainCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.DomainRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         domainId: "domainId"
 *     }
 */
export interface DomainFindRequest {
    landscapeId: string;
    versionId: string;
    domainId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         domainId: "domainId",
 *         name: "name"
 *     }
 */
export interface DomainUpsertRequest {
    landscapeId: string;
    versionId: string;
    domainId: string;
    commit?: number;
    index?: number;
    labels?: Record<string, string>;
    name: string;
    handleId?: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         domainId: "domainId"
 *     }
 */
export interface DomainDeleteRequest {
    landscapeId: string;
    versionId: string;
    domainId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         domainId: "domainId",
 *         body: {}
 *     }
 */
export interface DomainUpdateRequest {
    landscapeId: string;
    versionId: string;
    domainId: string;
    body: IcePanel.DomainPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         domainId: "domainId"
 *     }
 */
export interface DomainExistsRequest {
    landscapeId: string;
    versionId: string;
    domainId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface DraftsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.DraftFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             name: "name",
 *             status: "in-progress"
 *         }
 *     }
 */
export interface DraftCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.DraftRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         draftId: "draftId"
 *     }
 */
export interface DraftFindRequest {
    landscapeId: string;
    versionId: string;
    draftId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         draftId: "draftId",
 *         body: {
 *             name: "name",
 *             status: "in-progress"
 *         }
 *     }
 */
export interface DraftUpsertRequest {
    landscapeId: string;
    versionId: string;
    draftId: string;
    body: IcePanel.DraftRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         draftId: "draftId"
 *     }
 */
export interface DraftDeleteRequest {
    landscapeId: string;
    versionId: string;
    draftId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         draftId: "draftId",
 *         body: {}
 *     }
 */
export interface DraftUpdateRequest {
    landscapeId: string;
    versionId: string;
    draftId: string;
    body: IcePanel.DraftPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         draftId: "draftId"
 *     }
 */
export interface DraftMergeRequest {
    landscapeId: string;
    versionId: string;
    draftId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface FlowsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.FlowFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             name: "name",
 *             diagramId: "diagramId"
 *         }
 *     }
 */
export interface FlowCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.FlowRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId"
 *     }
 */
export interface FlowFindRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId",
 *         body: {
 *             name: "name",
 *             diagramId: "diagramId"
 *         }
 *     }
 */
export interface FlowUpsertRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
    body: IcePanel.FlowRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId"
 *     }
 */
export interface FlowDeleteRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId",
 *         body: {}
 *     }
 */
export interface FlowUpdateRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
    body: IcePanel.FlowPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId"
 *     }
 */
export interface FlowExistsRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface FlowThumbnailsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.DiagramFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId"
 *     }
 */
export interface FlowThumbnailGetRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId"
 *     }
 */
export interface LandscapeFindRequest {
    landscapeId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId"
 *     }
 */
export interface LandscapeDeleteRequest {
    landscapeId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         body: {}
 *     }
 */
export interface LandscapeUpdateRequest {
    landscapeId: string;
    body: IcePanel.LandscapePartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         body: {
 *             name: "name"
 *         }
 *     }
 */
export interface LandscapeDuplicateRequest {
    landscapeId: string;
    targetOrganizationId?: string;
    body: IcePanel.LandscapeRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         targetLandscapeId: "targetLandscapeId"
 *     }
 */
export interface LandscapeCopyRequest {
    landscapeId: string;
    targetLandscapeId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         search: "search"
 *     }
 */
export interface LandscapeSearchRequest {
    landscapeId: string;
    versionId: string;
    search: string;
    filter?: IcePanel.SearchFilter;
    includeData?: boolean;
    maxResults?: number;
}

/**
 * @example
 *     {}
 */
export interface OrganizationsListRequest {
    /** list all organizations on the platform */
    admin?: boolean;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationFindRequest {
    organizationId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationDeleteRequest {
    organizationId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         body: {}
 *     }
 */
export interface OrganizationUpdateRequest {
    organizationId: string;
    body: IcePanel.OrganizationPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface ShareLinkFindRequest {
    landscapeId: string;
    versionId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             "protected": true
 *         }
 *     }
 */
export interface ShareLinkCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.ShareLinkRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface ShareLinkDeleteRequest {
    landscapeId: string;
    versionId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {}
 *     }
 */
export interface ShareLinkUpdateRequest {
    landscapeId: string;
    versionId: string;
    resetShortId?: boolean;
    body: IcePanel.ShareLinkPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface TagsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.TagFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             color: "blue",
 *             groupId: "groupId",
 *             index: 1.1,
 *             name: "name"
 *         }
 *     }
 */
export interface TagCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.TagRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         tagId: "tagId"
 *     }
 */
export interface TagFindRequest {
    landscapeId: string;
    versionId: string;
    tagId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         tagId: "tagId",
 *         color: "blue",
 *         groupId: "groupId",
 *         index: 1.1,
 *         name: "name"
 *     }
 */
export interface TagUpsertRequest {
    landscapeId: string;
    versionId: string;
    tagId: string;
    color: IcePanel.TagColor;
    commit?: number;
    groupId: string;
    index: number;
    labels?: Record<string, string>;
    name: string;
    handleId?: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         tagId: "tagId"
 *     }
 */
export interface TagDeleteRequest {
    landscapeId: string;
    versionId: string;
    tagId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         tagId: "tagId",
 *         body: {}
 *     }
 */
export interface TagUpdateRequest {
    landscapeId: string;
    versionId: string;
    tagId: string;
    body: IcePanel.TagPartial;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface TeamsListRequest {
    organizationId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         body: {
 *             name: "name"
 *         }
 *     }
 */
export interface TeamCreateRequest {
    organizationId: string;
    body: IcePanel.TeamRequired;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         teamId: "teamId"
 *     }
 */
export interface TeamFindRequest {
    organizationId: string;
    teamId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         teamId: "teamId"
 *     }
 */
export interface TeamDeleteRequest {
    organizationId: string;
    teamId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         teamId: "teamId",
 *         body: {}
 *     }
 */
export interface TeamUpdateRequest {
    organizationId: string;
    teamId: string;
    body: IcePanel.TeamPartial;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         teamId: "teamId"
 *     }
 */
export interface TeamLandscapesListRequest {
    organizationId: string;
    teamId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         teamId: "teamId"
 *     }
 */
export interface TeamModelObjectsListRequest {
    organizationId: string;
    teamId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId"
 *     }
 */
export interface VersionsListRequest {
    landscapeId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         body: {
 *             name: "name",
 *             notes: "notes"
 *         }
 *     }
 */
export interface VersionCreateRequest {
    landscapeId: string;
    body: IcePanel.VersionRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface VersionFindRequest {
    landscapeId: string;
    versionId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface VersionDeleteRequest {
    landscapeId: string;
    versionId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {}
 *     }
 */
export interface VersionUpdateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.VersionPartial;
}

/**
 * @example
 *     {}
 */
export interface CatalogTechnologiesListRequest {
    filter?: IcePanel.CatalogTechnologyFilter;
    /** list all technologies on the platform */
    admin?: boolean;
}

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface CatalogSuggestionInformationGetRequest {
    url: string;
}

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface CatalogSuggestionBrandGetRequest {
    url: string;
}

/**
 * @example
 *     {
 *         catalogTechnologyId: "catalogTechnologyId"
 *     }
 */
export interface CatalogTechnologyFindRequest {
    catalogTechnologyId: string;
}

/**
 * @example
 *     {
 *         catalogTechnologySlug: "catalogTechnologySlug"
 *     }
 */
export interface CatalogTechnologySlugFindRequest {
    catalogTechnologySlug: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId"
 *     }
 */
export interface CommentRepliesListRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId",
 *         body: {
 *             content: "content"
 *         }
 *     }
 */
export interface CommentReplyCreateRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
    body: IcePanel.CommentReplyRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId",
 *         commentReplyId: "commentReplyId"
 *     }
 */
export interface CommentReplyFindRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
    commentReplyId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId",
 *         commentReplyId: "commentReplyId",
 *         content: "content"
 *     }
 */
export interface CommentReplyUpsertRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
    commentReplyId: string;
    content: string;
    mentionedUserIds?: string[];
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId",
 *         commentReplyId: "commentReplyId"
 *     }
 */
export interface CommentReplyDeleteRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
    commentReplyId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         commentId: "commentId",
 *         commentReplyId: "commentReplyId",
 *         body: {}
 *     }
 */
export interface CommentReplyUpdateRequest {
    landscapeId: string;
    versionId: string;
    commentId: string;
    commentReplyId: string;
    body: IcePanel.CommentReplyPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId"
 *     }
 */
export interface DiagramContentFindRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    updateViewedAt?: boolean;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId",
 *         body: {}
 *     }
 */
export interface DiagramContentReplaceRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    updateViewedAt?: boolean;
    body: IcePanel.DiagramContentRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId",
 *         body: {}
 *     }
 */
export interface DiagramContentUpdateRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    updateViewedAt?: boolean;
    body: IcePanel.DiagramContentPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface DiagramGroupsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.DiagramGroupFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             modelId: "modelId",
 *             name: "name"
 *         }
 *     }
 */
export interface DiagramGroupCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.DiagramGroupRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramGroupId: "diagramGroupId"
 *     }
 */
export interface DiagramGroupFindRequest {
    landscapeId: string;
    versionId: string;
    diagramGroupId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramGroupId: "diagramGroupId",
 *         modelId: "modelId",
 *         name: "name"
 *     }
 */
export interface DiagramGroupUpsertRequest {
    landscapeId: string;
    versionId: string;
    diagramGroupId: string;
    commit?: number;
    index?: number;
    labels?: Record<string, string>;
    modelId: string;
    name: string;
    handleId?: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramGroupId: "diagramGroupId"
 *     }
 */
export interface DiagramGroupDeleteRequest {
    landscapeId: string;
    versionId: string;
    diagramGroupId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramGroupId: "diagramGroupId",
 *         body: {}
 *     }
 */
export interface DiagramGroupUpdateRequest {
    landscapeId: string;
    versionId: string;
    diagramGroupId: string;
    body: IcePanel.DiagramGroupPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramGroupId: "diagramGroupId"
 *     }
 */
export interface DiagramGroupExistsRequest {
    landscapeId: string;
    versionId: string;
    diagramGroupId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId",
 *         diagramExportImageId: "diagramExportImageId"
 *     }
 */
export interface DiagramExportImageFindRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    diagramExportImageId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         diagramId: "diagramId",
 *         body: {}
 *     }
 */
export interface DiagramExportImageCreateRequest {
    landscapeId: string;
    versionId: string;
    diagramId: string;
    body: IcePanel.DiagramExportImageOptions;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId"
 *     }
 */
export interface FlowExportTextRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId"
 *     }
 */
export interface FlowExportCodeRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         flowId: "flowId"
 *     }
 */
export interface FlowExportMermaidRequest {
    landscapeId: string;
    versionId: string;
    flowId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId"
 *     }
 */
export interface ActionLogsListRequest {
    landscapeId: string;
    filter?: IcePanel.ActionLogFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         actionLogId: "actionLogId"
 *     }
 */
export interface ActionLogFindRequest {
    landscapeId: string;
    actionLogId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         actionLogId: "actionLogId"
 *     }
 */
export interface ActionLogChildrenListRequest {
    landscapeId: string;
    actionLogId: string;
    filter?: IcePanel.ActionLogFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         type: "pdf",
 *         body: {}
 *     }
 */
export interface LandscapeExportRequest {
    landscapeId: string;
    versionId: string;
    type: IcePanel.LandscapeExportType;
    filter?: IcePanel.LandscapeExportFilter;
    body: IcePanel.LandscapeExportOptions;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         landscapeExportId: "landscapeExportId"
 *     }
 */
export interface LandscapeExportFindRequest {
    landscapeId: string;
    versionId: string;
    landscapeExportId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId"
 *     }
 */
export interface ActionLogStatsByTypeRequest {
    landscapeId: string;
    filter?: IcePanel.ActionLogStatsFilter;
    period?: IcePanel.ActionLogStatsPeriod;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId"
 *     }
 */
export interface ActionLogStatsByEntityRequest {
    landscapeId: string;
    filter?: IcePanel.ActionLogStatsFilter;
    period?: IcePanel.ActionLogStatsPeriod;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface ModelConnectionsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.ModelConnectionFilter;
    expand?: IcePanel.ModelConnectionExpandKey | IcePanel.ModelConnectionExpandKey[];
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             name: "name",
 *             originId: "originId",
 *             targetId: "targetId"
 *         }
 *     }
 */
export interface ModelConnectionCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.ModelConnectionRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelConnectionId: "modelConnectionId"
 *     }
 */
export interface ModelConnectionFindRequest {
    landscapeId: string;
    versionId: string;
    modelConnectionId: string;
    expand?: IcePanel.ModelConnectionExpandKey | IcePanel.ModelConnectionExpandKey[];
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelConnectionId: "modelConnectionId",
 *         name: "name",
 *         originId: "originId",
 *         targetId: "targetId"
 *     }
 */
export interface ModelConnectionUpsertRequest {
    landscapeId: string;
    versionId: string;
    modelConnectionId: string;
    originConnector?: IcePanel.model.ConnectionsUpsertRequestOriginConnector;
    targetConnector?: IcePanel.model.ConnectionsUpsertRequestTargetConnector;
    updateDiagrams?: boolean;
    commit?: number;
    description?: string;
    direction?: unknown;
    labels?: Record<string, string>;
    links?: unknown;
    name: string;
    /** Model object that initiates the connection */
    originId: string;
    status?: IcePanel.ModelConnectionStatus;
    tagIds?: unknown;
    /** Model object that receives the message */
    targetId: string;
    technologyIds?: unknown;
    viaId?: unknown;
    handleId?: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelConnectionId: "modelConnectionId"
 *     }
 */
export interface ModelConnectionDeleteRequest {
    landscapeId: string;
    versionId: string;
    modelConnectionId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelConnectionId: "modelConnectionId",
 *         body: {}
 *     }
 */
export interface ModelConnectionUpdateRequest {
    landscapeId: string;
    versionId: string;
    modelConnectionId: string;
    updateDiagrams?: boolean;
    body: IcePanel.ModelConnectionPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface ModelObjectsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.ModelObjectFilter;
    expand?: IcePanel.ModelObjectExpandKey | IcePanel.ModelObjectExpandKey[];
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             name: "name",
 *             type: "actor"
 *         }
 *     }
 */
export interface ModelObjectCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.ModelObjectRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelObjectId: "modelObjectId"
 *     }
 */
export interface ModelObjectFindRequest {
    landscapeId: string;
    versionId: string;
    modelObjectId: string;
    expand?: IcePanel.ModelObjectExpandKey | IcePanel.ModelObjectExpandKey[];
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelObjectId: "modelObjectId",
 *         name: "name",
 *         type: "actor"
 *     }
 */
export interface ModelObjectUpsertRequest {
    landscapeId: string;
    versionId: string;
    modelObjectId: string;
    /** Short summary of the object shown as the display description */
    caption?: string;
    commit?: number;
    description?: string;
    external?: boolean;
    groupIds?: unknown;
    icon?: IcePanel.ModelObjectIconNullable | null;
    /** Generic key value store used for creating custom integrations */
    labels?: Record<string, string>;
    links?: unknown;
    name: string;
    parentId?: unknown;
    status?: IcePanel.ModelObjectStatus;
    tagIds?: unknown;
    teamIds?: unknown;
    /** Model object (+child diagram, diagram groups and flows) can only be edited by owners and admins */
    teamOnlyEditing?: boolean;
    technologyIds?: unknown;
    type: IcePanel.ModelObjectType;
    domainId?: string;
    handleId?: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelObjectId: "modelObjectId"
 *     }
 */
export interface ModelObjectDeleteRequest {
    landscapeId: string;
    versionId: string;
    modelObjectId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelObjectId: "modelObjectId",
 *         body: {}
 *     }
 */
export interface ModelObjectUpdateRequest {
    landscapeId: string;
    versionId: string;
    modelObjectId: string;
    body: IcePanel.ModelObjectPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface ModelConnectionsExportCsvRequest {
    landscapeId: string;
    versionId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         modelObjectId: "modelObjectId"
 *     }
 */
export interface ModelObjectDependenciesExportJsonRequest {
    landscapeId: string;
    versionId: string;
    modelObjectId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface ModelObjectsExportCsvRequest {
    landscapeId: string;
    versionId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationLandscapesListRequest {
    organizationId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         name: "name"
 *     }
 */
export interface OrganizationLandscapeCreateRequest extends IcePanel.LandscapeRequired {
    organizationId: string;
    backstageEntities?: IcePanel.BackstageEntityMap;
    structurizrWorkspace?: IcePanel.StructurizrWorkspace;
    templateId?: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationLogsListRequest {
    organizationId: string;
    filter?: IcePanel.OrganizationLogFilter;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         organizationLogId: "organizationLogId"
 *     }
 */
export interface OrganizationLogFindRequest {
    organizationId: string;
    organizationLogId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationTechnologiesListRequest {
    organizationId: string;
    filter?: IcePanel.CatalogTechnologyFilter;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         body: {
 *             color: "blue",
 *             name: "name"
 *         }
 *     }
 */
export interface OrganizationTechnologyCreateRequest {
    organizationId: string;
    body: IcePanel.CatalogTechnologyRequired;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         catalogTechnologyId: "catalogTechnologyId"
 *     }
 */
export interface OrganizationTechnologyFindRequest {
    organizationId: string;
    catalogTechnologyId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         catalogTechnologyId: "catalogTechnologyId"
 *     }
 */
export interface OrganizationTechnologyDeleteRequest {
    organizationId: string;
    catalogTechnologyId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         catalogTechnologyId: "catalogTechnologyId",
 *         body: {}
 *     }
 */
export interface OrganizationTechnologyUpdateRequest {
    organizationId: string;
    catalogTechnologyId: string;
    body: IcePanel.CatalogTechnologyPartial;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationUsersListRequest {
    organizationId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         userId: "userId"
 *     }
 */
export interface OrganizationUserDeleteRequest {
    organizationId: string;
    userId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         userId: "userId",
 *         body: {
 *             permission: "billing"
 *         }
 *     }
 */
export interface OrganizationUserUpdateRequest {
    organizationId: string;
    userId: string;
    body: IcePanel.OrganizationUser;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationLogStatsByTypeRequest {
    organizationId: string;
    filter?: IcePanel.OrganizationLogStatsFilter;
    period?: IcePanel.ActionLogStatsPeriod;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationLogStatsByEntityRequest {
    organizationId: string;
    filter?: IcePanel.OrganizationLogStatsFilter;
    period?: IcePanel.ActionLogStatsPeriod;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId"
 *     }
 */
export interface OrganizationUserInvitesListRequest {
    organizationId: string;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         body: {
 *             email: "email",
 *             expiresAt: "2024-01-15T09:30:00Z",
 *             permission: "billing"
 *         }
 *     }
 */
export interface OrganizationUserInviteCreateRequest {
    organizationId: string;
    body: IcePanel.OrganizationUserInviteRequired;
}

/**
 * @example
 *     {
 *         organizationId: "organizationId",
 *         organizationUserInviteId: "organizationUserInviteId"
 *     }
 */
export interface OrganizationUserInviteRevokeRequest {
    organizationId: string;
    organizationUserInviteId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId"
 *     }
 */
export interface TagGroupsListRequest {
    landscapeId: string;
    versionId: string;
    filter?: IcePanel.TagGroupFilter;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         body: {
 *             icon: "bug",
 *             index: 1.1,
 *             name: "name"
 *         }
 *     }
 */
export interface TagGroupCreateRequest {
    landscapeId: string;
    versionId: string;
    body: IcePanel.TagGroupRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         tagGroupId: "tagGroupId"
 *     }
 */
export interface TagGroupFindRequest {
    landscapeId: string;
    versionId: string;
    tagGroupId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         tagGroupId: "tagGroupId",
 *         icon: "bug",
 *         index: 1.1,
 *         name: "name"
 *     }
 */
export interface TagGroupUpsertRequest {
    landscapeId: string;
    versionId: string;
    tagGroupId: string;
    commit?: number;
    icon: IcePanel.TagGroupIcon;
    index: number;
    labels?: Record<string, string>;
    name: string;
    handleId?: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         tagGroupId: "tagGroupId"
 *     }
 */
export interface TagGroupDeleteRequest {
    landscapeId: string;
    versionId: string;
    tagGroupId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionId: "versionId",
 *         tagGroupId: "tagGroupId",
 *         body: {}
 *     }
 */
export interface TagGroupUpdateRequest {
    landscapeId: string;
    versionId: string;
    tagGroupId: string;
    body: IcePanel.TagGroupPartial;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId"
 *     }
 */
export interface VersionRevertsListRequest {
    landscapeId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         body: {
 *             notes: "notes",
 *             versionId: "versionId"
 *         }
 *     }
 */
export interface VersionRevertCreateRequest {
    landscapeId: string;
    body: IcePanel.VersionRevertRequired;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionRevertId: "versionRevertId"
 *     }
 */
export interface VersionRevertFindRequest {
    landscapeId: string;
    versionRevertId: string;
}

/**
 * @example
 *     {
 *         landscapeId: "landscapeId",
 *         versionRevertId: "versionRevertId",
 *         body: {}
 *     }
 */
export interface VersionRevertUpdateRequest {
    landscapeId: string;
    versionRevertId: string;
    body: IcePanel.VersionRevertPartial;
}
